export const unitService=[
    {
        number:0,
        hexValue:"0x00",
        unit:'mV/V',
        symbol:'mv/V',
        ratio:1
    },
    {
        number:45,
        hexValue:"0x2D",
        unit:'kilograms',
        symbol:'kg',
        ratio:1
    },
    {
        number:48,
        hexValue:"0x30",
        unit:'grams',
        symbol:'g',
        ratio:1000
    },
    {
        number:49,
        hexValue:"0x31",
        unit:'milligrams',
        symbol:'mg',
        ratio:1000000
    },
    {
        number:52,
        hexValue:"0x34",
        unit:'pounds',
        symbol:'lb',
        ratio:2.204585538
    },
    {
        number:53,
        hexValue:"0x35",
        unit:'kilopounds',
        symbol:'klb',
        ratio:2.204585538
    },
    {
        number:56,
        hexValue:"0x38",
        unit:'tons long',
        symbol:'ton',
        ratio:9.84E-04
    },
    {
        number:65,
        hexValue:"0x41",
        unit:'newtons',
        symbol:'N',
        ratio:9.80665
    },
    {
        number:66,
        hexValue:"0x42",
        unit:'kilonewtons',
        symbol:'kN',
        ratio:0.00980665
    },
    {
        number:71,
        hexValue:"0x47",
        unit:'grams force',
        symbol:'gf',
        ratio:0.1000
    },
    {
        number:73,
        hexValue:"0x49",
        unit:'kilograms force',
        symbol:'kgf',
        ratio:1
    },
    {
        number:75,
        hexValue:"0x4B",
        unit:'kilograms meter/second²',
        symbol:'kg ms²',
        ratio:1
    },
    {
        number:77,
        hexValue:"0x4D",
        unit:'pounds force',
        symbol:'lbf',
        ratio:2.204622622
    },
]
